# This file is automatically generated by pybind11-stubgen and generate_stubs.py
#
# Automatically generated files do not have a copyright

from __future__ import annotations
import logging as logging
import rmf2_scheduler._core.log
from rmf2_scheduler._core.log import LogLevel
from rmf2_scheduler._core.log import get_log_level
from rmf2_scheduler._core.log import log
from rmf2_scheduler._core.log import register_log_handler
from rmf2_scheduler._core.log import set_log_level
from rmf2_scheduler._core.log import unregister_log_handler
__all__: list[str] = ['LogLevel', 'get_log_level', 'log', 'logging', 'register_log_handler', 'register_python_logger', 'set_log_level', 'unregister_log_handler']
def _log_callback(file: str, line: int, loglevel: rmf2_scheduler._core.log.LogLevel, log: str) -> None:
    ...
def register_python_logger() -> None:
    """
    Register a callback that forwards every native log message to a Python logger.
    """
_LEVEL_TO_LOGGING: dict  # value = {<LogLevel.DEBUG: 0>: 10, <LogLevel.INFO: 1>: 20, <LogLevel.WARN: 2>: 30, <LogLevel.ERROR: 3>: 40, <LogLevel.FATAL: 4>: 50, <LogLevel.NONE: 5>: 0}
_LOGGER: logging.Logger  # value = <Logger rmf2_scheduler.log (INFO)>
