# This file is automatically generated by pybind11-stubgen and generate_stubs.py
#
# Automatically generated files do not have a copyright

from __future__ import annotations
__all__: list[str] = ['EVENT', 'PROCESS', 'SERIES', 'TASK']
EVENT: str = 'event'
PROCESS: str = 'process'
SERIES: str = 'series'
TASK: str = 'task'
