# This file is automatically generated by pybind11-stubgen and generate_stubs.py
#
# Automatically generated files do not have a copyright

from __future__ import annotations
__all__: list[str] = ['ADD', 'DELETE', 'UPDATE']
ADD: str = 'add'
DELETE: str = 'delete'
UPDATE: str = 'update'
