# This file is automatically generated by pybind11-stubgen and generate_stubs.py
#
# Automatically generated files do not have a copyright

from __future__ import annotations
import typing
__all__: list[str] = ['LogLevel', 'get_log_level', 'log', 'register_log_handler', 'set_log_level', 'unregister_log_handler']
class LogLevel:
    """
    Members:
    
      DEBUG
    
      INFO
    
      WARN
    
      ERROR
    
      FATAL
    
      NONE
    """
    DEBUG: typing.ClassVar[LogLevel]  # value = <LogLevel.DEBUG: 0>
    ERROR: typing.ClassVar[LogLevel]  # value = <LogLevel.ERROR: 3>
    FATAL: typing.ClassVar[LogLevel]  # value = <LogLevel.FATAL: 4>
    INFO: typing.ClassVar[LogLevel]  # value = <LogLevel.INFO: 1>
    NONE: typing.ClassVar[LogLevel]  # value = <LogLevel.NONE: 5>
    WARN: typing.ClassVar[LogLevel]  # value = <LogLevel.WARN: 2>
    __members__: typing.ClassVar[dict[str, LogLevel]]  # value = {'DEBUG': <LogLevel.DEBUG: 0>, 'INFO': <LogLevel.INFO: 1>, 'WARN': <LogLevel.WARN: 2>, 'ERROR': <LogLevel.ERROR: 3>, 'FATAL': <LogLevel.FATAL: 4>, 'NONE': <LogLevel.NONE: 5>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
def get_log_level() -> LogLevel:
    """
    Get current log level.
    """
def log(file: str, line: int, loglevel: LogLevel, message: str) -> None:
    """
    Emit a log message through the currently registered log handler.
    """
def register_log_handler(callback: typing.Callable[[str, int, LogLevel, str], None]) -> None:
    """
    Register callback(file, line, loglevel, log) to handle log messages.
    """
def set_log_level(arg0: LogLevel) -> None:
    """
    Set log level this will disable messages with lower log level.
    """
def unregister_log_handler() -> None:
    """
    Unregister current log handler, this will enable default log handler.
    """
