# This file is automatically generated by pybind11-stubgen and generate_stubs.py
#
# Automatically generated files do not have a copyright

from __future__ import annotations
import rmf2_scheduler._core.cache
import rmf2_scheduler._core.data
import typing
__all__: list[str] = ['ScheduleStream']
class ScheduleStream:
    """
    
        Stream for the schedule
        
    """
    @staticmethod
    def create_default(arg0: str) -> ScheduleStream:
        ...
    @staticmethod
    def create_simple(arg0: int, arg1: str) -> ScheduleStream:
        ...
    def read_schedule(self, arg0: rmf2_scheduler._core.cache.ScheduleCache, arg1: rmf2_scheduler._core.data.TimeWindow) -> tuple:
        ...
    @typing.overload
    def write_schedule(self, arg0: rmf2_scheduler._core.cache.ScheduleCache, arg1: rmf2_scheduler._core.data.TimeWindow) -> tuple:
        ...
    @typing.overload
    def write_schedule(self, arg0: rmf2_scheduler._core.cache.ScheduleCache, arg1: list[rmf2_scheduler._core.data.ScheduleChangeRecord]) -> tuple:
        ...
