# This file is automatically generated by pybind11-stubgen and generate_stubs.py
#
# Automatically generated files do not have a copyright

from __future__ import annotations

import typing

import rmf2_scheduler._core.data

__all__ = ['TreeConversion']
class TreeConversion:
    """
    
        DAG to Behavior Tree
        
    """
    def __init__(self) -> None:
        ...
    @typing.overload
    def convert_to_tree(self, arg0: rmf2_scheduler._core.data.Graph, arg1: typing.Callable[[str], str]) -> str:
        ...
    @typing.overload
    def convert_to_tree(self, arg0: str, arg1: rmf2_scheduler._core.data.Graph, arg2: typing.Callable[[str], str]) -> str:
        ...
